FROM golang:1.19-buster as builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN go build -v -o server ./cmd/api_gateway/main.go

FROM debian:buster-slim 
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/server /app/server
COPY --from=builder /app/pkg/api_gateway/config/config-docker.yml /app/pkg/api_gateway/config/config-docker.yml

ENV APP_ENV docker
ENV PORT ${Port}

CMD [ "/app/server" ]
 